import type { JobseekerRegistrationData } from "./jobseeker-registration";

/**
 * Default form values for jobseeker registration and edit.
 * Used by form-layout and record-to-form mapper so create and edit share one source of truth.
 * Initial state uses empty strings for required-enum fields until the user selects a value.
 */
export const JOBSEEKER_REGISTRATION_DEFAULTS = {
  personalInfo: {
    surname: "",
    firstName: "",
    middleName: "",
    suffix: "",
    dateOfBirth: "",
    placeOfBirth: "",
    sex: "",
    religion: "",
    civilStatus: "",
    address: {
      houseStreet: "",
      barangay: "",
      city: "",
      province: "",
    },
    tin: "",
    disability: {
      visual: false,
      hearing: false,
      speech: false,
      physical: false,
      mental: false,
      others: "",
    },
    height: "",
    contactNumber: "",
    email: "",
  },
  employment: {
    status: "",
    employedType: "",
    selfEmployedTypes: {
      fisherman: false,
      vendor: false,
      homeBased: false,
      transport: false,
      domestic: false,
      freelancer: false,
      artisan: false,
      others: "",
    },
    unemployedReason: "",
    terminatedCountry: "",
    unemployedReasonOthers: "",
    jobSearchDuration: "",
    isOfw: false,
    ofwCountry: "",
    isFormerOfw: false,
    formerOfwCountry: "",
    ofwReturnDate: "",
    is4PsBeneficiary: false,
    householdIdNumber: "",
  },
  jobPreference: {
    employmentType: "",
    occupation1: "",
    occupation2: "",
    occupation3: "",
    localLocation1: "",
    localLocation2: "",
    localLocation3: "",
    overseasLocation1: "",
    overseasLocation2: "",
    overseasLocation3: "",
  },
  language: {
    english: {
      read: false,
      write: false,
      speak: false,
      understand: false,
    },
    filipino: {
      read: false,
      write: false,
      speak: false,
      understand: false,
    },
    mandarin: {
      read: false,
      write: false,
      speak: false,
      understand: false,
    },
    othersName: "",
    others: {
      read: false,
      write: false,
      speak: false,
      understand: false,
    },
  },
  education: {
    currentlyInSchool: false,
    elementary: {
      yearGraduated: "",
      levelReached: "",
      yearLastAttended: "",
    },
    secondary: {
      curriculumType: undefined,
      yearGraduated: "",
      levelReached: "",
      yearLastAttended: "",
    },
    k12: {
      yearGraduated: "",
      levelReached: "",
      yearLastAttended: "",
    },
    seniorHigh: {
      strand: "",
      yearGraduated: "",
      levelReached: undefined,
      yearLastAttended: "",
    },
    tertiary: {
      course: "",
      yearGraduated: "",
      levelReached: "",
      yearLastAttended: "",
    },
    graduate: {
      course: "",
      yearGraduated: "",
      yearLastAttended: "",
    },
    postGraduate: {
      course: "",
      yearGraduated: "",
      yearLastAttended: "",
    },
  },
  training: {
    entries: [],
  },
  eligibility: {
    civilService: [],
    professionalLicense: [],
  },
  workExperience: {
    entries: [],
  },
  skills: {
    otherSkills: {
      auto_mechanic: false,
      beautician: false,
      carpentry_work: false,
      computer_literate: false,
      domestic_chores: false,
      driver: false,
      electrician: false,
      embroidery: false,
      gardening: false,
      masonry: false,
      painter_artist: false,
      painting_jobs: false,
      photography: false,
      plumbing: false,
      sewing_dresses: false,
      stenography: false,
      tailoring: false,
      others: "",
    },
    certification: {
      acknowledged: false,
      signature: "",
      dateSigned: "",
    },
    pesoUseOnly: {
      referralPrograms: {
        spes: false,
        gip: false,
        tupad: false,
        jobstart: false,
        dileep: false,
        tesda_training: false,
        others: "",
      },
      assessedBy: "",
      assessorSignature: "",
      assessmentDate: "",
    },
  },
} as unknown as JobseekerRegistrationData;
